### ISSUE TITLE
Editing pane area permanently shrunken

### ISSUE THREAD

**Issue by Brendan-McDonnell** [timomeh/hey-pane#23] opened 2018-08-01 17:05 UTC
Full pane editing area somehow locked into a very small section.
![hey pane bug image](https://user-images.githubusercontent.com/36059032/43536394-5674440a-9571-11e8-9b3b-e19d1239d0d2.png)
In this photo, I have two panes open side by side: Settings and a file. However, both of them take up a very small portion of the total screen.

The width of the area in which I can put panels cannot be changed by using multiple panes side by side or any other method I have tried. There is also no resizing functionality.

I have not been able to add or move any sort of pane into the large blank space, only within the small strip.

I have tried disabling Hey Pane and restarting atom to no avail. The Hey Pane commands also do not fix this issue.

As **this issue persists even with Hey Pane disabled, Atom becomes fully unusable** with this bug.

**Comment by timomeh** [comment] 2018-08-01 18:46
Hi, and thanks for reporting! Unfortunately I cannot reproduce the error, so I need more informations:

- When did this happen? Right after you focused a pane with hey-pane? Can you please provide steps in order to reproduce the error?
- Please tell me your Atom Version (`atom --version`) and the Plugins you have installed (`apm list`).

From the screenshot it seems that your pane-container (the UI section which holds all editor pane) was resized. Technically hey-pane only resizes panes _inside_ the pane-container, and not the container itself.

**Comment by Brendan-McDonnell** [comment] 2018-08-02 20:29
Unfortunately, I am unsure of exactly what I was doing when I caused this error. I had just installed multiple packages to help with my UI. All I am aware of is that I was experimenting with the Hey Pane commands when this issue initially occurred.

Versions:
Atom    : 1.29.0
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3

Community Packages:
├── atom-beautify@0.32.5 (disabled)
├── atom-clock@0.1.16 (disabled)
├── atom-ide-ui@0.13.0 (disabled)
├── atom-live-server@2.3.0 (disabled)
├── atom-material-syntax@1.0.8
├── atom-material-syntax-dark@1.0.0
├── atom-material-ui@2.1.3
├── autoclose-html@0.23.0 (disabled)
├── busy-signal@1.4.3 (disabled)
├── dark-bint-syntax@0.10.0
├── gl-dark-syntax@3.0.0
├── google-dark-syntax@3.3.0
├── grandson-of-obsidian@0.1.0
├── hey-pane@1.1.0 (disabled)
├── html-to-css@0.2.2 (disabled)
├── ide-css@0.3.0 (disabled)
├── ide-html@0.4.2 (disabled)
├── ide-json@0.2.1 (disabled)
├── intentions@1.1.5 (disabled)
├── linter@2.2.0 (disabled)
├── linter-ui-default@1.7.1 (disabled)
├── minimap@4.29.8 (disabled)
├── obsidian-colors-syntax@1.0.0
├── pigments@0.40.2 (disabled)
├── script@3.18.1 (disabled)
├── teletype@0.13.3 (disabled)
├── todo-show@2.3.0 (disabled)
└── zero-dark-matrix-syntax@1.1.1

I have disabled all community packages to no avail. However, starting in safe mode works fine.

**Comment by Brendan-McDonnell** [comment] 2018-08-02 20:29
**Update:**
I started to inspected the differences with the atom-pane-container and atom-pane between my normal Atom set up and the working safe mode. I found that my pane had its flex-grow property set to 0.06 for some reason, and my safe mode version had it set to 1. On changing that 0.06 to 1.0, my Atom panes returned to full functionality. I am now going to investigate what caused the issue to determine if it is unrelated to hey-pane.

**Comment by timomeh** [comment] 2018-08-02 20:40
If you toggle focus in hey-pane, it sets the flex of the active pane to `0.94` and the other panes to `0.06`. If you toggle focus again, hey-pane resets the flex values to their previous state.

But that shouldn't squish your pane-container down, like in your screenshot.

Could you please check your settings, in the "Core" Section there's a Setting for "Remove Empty Panes", which should be enabled by default. If you have _not_ enabled this setting, and you focused a pane with hey-pane and then closed all the editors inside it, the pane remains empty and expanded. With those steps I can reproduce your screenshot.

But even in this case the pane can be closed by doing a `Pane: Close` (cmd-w on a mac), and also hey-pane can still shrink the pane, _and_ you can still resize the pane with your mouse. So I don't know if that was really the case here.

**Comment by Brendan-McDonnell** [comment] 2018-08-02 21:34
I have "Remove Empty Panes" enabled.

**Narrowing down the issue**
I decided to find out the differences between my broken atom (atom-beautify@0.32.5 and hey-pane@1.1.0) and the safe atom (no community packages). I used beautify to make the HTML I was copying readable.

I opened the developer tools and copied the HTML of my atom-workspace-axis in both Atoms while having one empty untitled file. I then beautified the code for readability and put both into a difference comparison program. The result can be found [here](https://www.diffchecker.com/NjqBfSdE).

The only significant and relative difference I could find was that in my broken atom, my current pane had  `style="flex-grow: 0.06"` whereas the working atom had `style="flex-grow: 1"`.

While the safe version's pane was active and the broken was not, I believe that was due to what panel had focus when I opened the developer tools. I could be mistaken.

I also discovered something interesting: when I open the config folder from the broken Atom, the new window it opens works perfectly. Unsure of the cause, unless the config folder is always opened in safe mode.

**Possible cause**
The only section in which I can see anything having it's flex-grow set to 0.06 in hey-pane.js is when the panel's siblings are collapsed. Here's the snippet:

```
// ...and collapse all its siblings.
pane.getParent().children
.filter(el => el !== pane) // bcuz only siblings
.forEach(sibling => {
   this.savePaneState(sibling).setFlexScale(collapsedWidth)
})

// Do the same with the adjacent panes, until we're on the root axis.
   if (pane.getParent() !== paneRoot) {
      resursiveSet(pane.getParent())
   }
```

If this is what caused the issue (and what else would set it to be exactly 0.06?), then I am very confused as to how to fix it; it doesn't matter if the hey-pane plugin is even enabled, this issue persists permanently. I am also not sure what would have made this select itself/its parent, as it clearly selects its siblings. Perhaps some other plugin manipulated the panels concurrently.

This one has me quite confused, especially the permanent nature of the issue.

**Comment by timomeh** [comment] 2018-08-02 22:52
Thanks for your investigation, this helps a lot. You're right, the `flex-grow: 0.06` sure sounds like the hey-pane setting.

I reproduced the issue. I don't know how I did it (I just created panes, toggled the dock in and out, resized panes and the dock, created and closed more panes). **But** my pane is now stuck at `flex-grow: 0.71109`, not at `0.06` like yours. I can even manually set the pane to `flex-grow: 1` and the next time I split the pane it's back to `0.71109`. Even if I restart Atom, it keeps using `0.71109`.

This only happens (in my case) in one project workspace. The workspace in which I tinkered around when trying to reproduce the issue. All other projects are just fine.

Since the functionality from hey-pane is very simple (it doesn't store its state when restarting Atom, and it just executes when the command is triggered), and the issue persists even if hey-pane is disabled (which I can confirm), I don't think it's related to hey-pane.

Although your pane is exactly stuck at `0.06`, which obviously is the hey-pane setting, it seems like this bug simply happened while hey-pane was active. You toggled hey-pane, the inactive pane was resized to `0.06`, you tried out a few things, which triggered the bug, and it then remained stuck at `0.06`.

It sounds like somewhere in this scenario Atom stores an intermediate window state as the default window state for this workspace.

That being said, while I don't think hey-pane is immediately causing the issue, it might be a tool which can provoke it in a chaos-monkey-scenario. I still don't know exactly how to reproduce it, so I cannot be sure and don't know if/how to prevent this.

But it's really late now and I need to take a nap. 😅

## Workaround

You can clear the state for a project window by starting it through the CLI:

```
atom --clear-window-state path/to/weird/project
```

See https://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state:

> :rotating_light: Danger: Clearing the saved state permanently destroys any state that Atom has saved across all projects. This includes unsaved changes to files you may have been editing in all projects. This is a destructive action.

I used that and my messed up workspace now is fine again.

**Comment by timomeh** [comment] 2018-08-13 20:49
@Brendan-McDonnell Could you solve it using the workaround?

**Comment by timomeh** [comment] 2018-10-16 22:20
This issue is being closed due to inactivity. If there are still problems, please reopen.

**Closed by timomeh** 2018-10-16 22:20 UTC
